#! /usr/bin/env python

import os
from tabulate import tabulate

from src.database.ensure_db import ensure_langdb
from src.utils import get_arguments
from src import match_terms, map_terms_to_dictionary
from src.utils.classes import CommandLineInvocation


def scratch():
    print(tabulate([["value1", "value2"], ["value3", "value4"]], ["column 1", "column 2"], tablefmt="grid"))


def main():
    print('-------> inside: main')
    ROOT_DIR = os.path.dirname(os.path.abspath(__file__))  # This is your Project Root
    invoke = CommandLineInvocation(ROOT_DIR)

    ensure_langdb(invoke)

    invoke.arguments = get_arguments()
    invoke.arguments.term_split = invoke.arguments.term.split(' ')

    match_terms(invoke)
    map_terms_to_dictionary(invoke)

    invoke.connection.commit()
    invoke.connection.close()


main()
