#! /usr/bin/env python

import sqlite3
import os
from tabulate import tabulate

from src.database.ensure_db import ensure_langdb
from src.database.utils import print_table_from_cursor
from src.utils import get_arguments


def scratch():
    print(tabulate([["value1", "value2"], ["value3", "value4"]], ["column 1", "column 2"], tablefmt="grid"))


def main():
    ROOT_DIR = os.path.dirname(os.path.abspath(__file__))  # This is your Project Root
    print('<------- inside: main ------->')
    con = sqlite3.connect('{path}/langbase.sqlite'.format(path=ROOT_DIR))
    con.execute("PRAGMA foreign_keys = 1")
    cur = con.cursor()
    arguments = get_arguments()
    ensure_langdb(con, cur)
    arguments.term_split = arguments.term.split(' ')

    query = "SELECT * FROM term_matches WHERE term IN (%s)" % ','.join('?' * len(arguments.term_split))
    cur.execute(query, arguments.term_split)

    print_table_from_cursor(cur)

    con.commit()
    con.close()


main()
