#! /usr/bin/env python

import sqlite3
from tabulate import tabulate

from src.database.ensure_db import ensure_langdb
from src.utils import get_arguments


def scratch():
    print(tabulate([["value1", "value2"], ["value3", "value4"]], ["column 1", "column 2"], tablefmt="grid"))


def main():
    print('<------- inside: main ------->')
    con = sqlite3.connect('langbase.sqlite')
    cur = con.cursor()

    ensure_langdb(con, cur)

    con.commit()
    con.close()

    arguments = get_arguments()

    print(vars(arguments))

    print('-------> arguments.input: {}'.format(arguments.input))
    arguments.input_split = arguments.input.split(' ')
    print('-------> arguments.input_split: {}'.format(arguments.input_split))


main()
